plugins {
    id 'com.android.application'
}

android {
    namespace 'com.diskwalalinks.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.diskwalalinks.app"
        minSdk 23
        targetSdk 35
        versionCode 2
versionName "2.0"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
        }
    }
}
